[project]
# Whether to enable telemetry (default: true). No personal data is collected.
enable_telemetry = true

# List of environment variables to be provided by each user to use the app.
user_env = []

# Duration (in seconds) during which the session is saved when the connection is lost
session_timeout = 3600

[UI]
# Name of the app and chatbot.
name = "Geolocation Assistant"

# Description of the app and chatbot. This is used for HTML tags.
description = "A helpful assistant that finds locations based on coordinates"

# The default value for the input placeholder
input_placeholder = "Ask about a location (e.g., latitude 40.7128, longitude -74.0060)"

# Show the readme while the conversation is empty.
show_readme = true

# Hide the chain of thought details from the user.
hide_cot = false

# Custom theme
[UI.theme]
primary = "#FF69B4"  # Pink color for branding

# Logo configuration
[UI.logo]
path = "logo.png"
dark_mode_path = "logo_dark.png"  # Optional: different logo for dark mode 